spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/querydsl;
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true , 밑에 디버그랑 중복됨으로 이건 주석처리함
        format_sql: true
  #        dialect: org.hibernate.dialect.Oracle10gDialect
  #        default_batch_fetch_size: 100
  #    open-in-view: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
#        one-indexed-parameters: true //페이지가 1부터 시작하게됌, page의 추가 정보들은 안맞게됌.. 쓰지 말 것
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace 쿼리 ? 값을 볼 수 있음 근데 좀 불편하게 나옴